# DF002 — Initial Exploratory Investigation

## Task Classification

- EDA Task
- Criticidade: Medium
- Stakeholder principal: Customer Retention Manager

---

## Contexto Operacional

Após a validação estrutural inicial do dataset, a liderança de retenção precisa de uma primeira leitura exploratória do comportamento dos clientes.

Nesta etapa ainda não buscamos:

- conclusões executivas definitivas
- causalidade forte
- modelagem preditiva

O foco atual é produzir entendimento exploratório inicial e identificar possíveis padrões relacionados ao churn.

---

## Objetivo da Task

Executar primeira etapa de EDA focada em:

- entendimento do target (`Churn`)
- perfil geral dos clientes
- comportamento inicial das variáveis
- identificação de possíveis padrões associados ao churn

---

## Escopo Esperado

Nesta etapa o foco deve permanecer em:

1. Distribuição do target (`Churn`)
2. Análise univariada inicial
3. Análise bivariada introdutória com churn
4. Distribuições numéricas principais
5. Primeiros padrões relevantes
6. Possíveis variáveis de interesse

---

## Variáveis Prioritárias

Investigar com atenção especial:

- `tenure`
- `MonthlyCharges`
- `TotalCharges`
- `Contract`
- `InternetService`
- `PaymentMethod`

---

## Diretrizes Operacionais

Evitar:

- excesso de gráficos
- pairplots desnecessários
- dashboards extensos
- correlação sem interpretação
- storytelling exagerado

Priorizar:

- leitura analítica
- interpretação
- clareza investigativa
- observações objetivas
- exploração organizada

---

## Notebook Esperado

```text
03_initial_eda.ipynb
```

---

## Entregáveis Esperados

O notebook deve conter:

- markdowns interpretativos
- gráficos selecionados com critério
- leituras analíticas
- observações operacionais
- transições organizadas entre etapas

---

## Critérios de Aprovação

A entrega será avaliada considerando:

- clareza investigativa
- escolha adequada de visualizações
- interpretação analítica
- disciplina exploratória
- capacidade de síntese
- organização do notebook
- coerência metodológica

---

## Observação Importante

Na validação estrutural a principal pergunta era:

```text
"O dado é confiável?"
```

Agora, na EDA, a principal pergunta passa a ser:

```text
"O que o dado está tentando nos dizer?"
```

## 1. Contexto da Task

Na nossa task anterior [structural validation](./02_structural_validation.ipynb) focamos na integridade estrutural e na confiabilidade incial dos dads. Focamos na integralidade deles, reconhecendo tipos e verificando se é a melhor escolha, a presença de *missing datas* implícitos e explícitos, relações estruturais e coerência lógica entre colunas e duplicatas.

Nesse nova task iremos nos aprofundar mais. Queremos saber qual o comportamento geral de nossos dados, quais padrões existentes entre eles, verificar a existência de padrões analíticos e observar o comportamento da coluna `churn`. A ideia é criar um mapa mental macro e interpretar suas correlações e padrões. Algumas visualizações exploratórias poderão ser utilizadas para auxiliar na identificação de padrões e relações entre variáveis.

## 2. Imports e Setup

In [1]:
import pandas as pd

print(f"Versão do pandas: {pd.__version__}")

Versão do pandas: 2.2.2

In [2]:
df_origin = pd.read_csv(
    "../data/raw/telco-customer-churn/WA_Fn-UseC_-Telco-Customer-Churn.csv"
)
df = df_origin.copy()

In [3]:
df.head(3)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes

## 3. Visão Inicial do Tagert (`Churn`)

In [11]:
contagem_churn = df.Churn.value_counts().to_frame(name="contagem")
contagem_churn["%"] = (
    contagem_churn.contagem / contagem_churn.contagem.sum() * 100
).round(2)
contagem_churn

       contagem      %
Churn
No         5174  73.46
Yes        1869  26.54

Aproximadamente 1 e cada 4 clientes apresentou churn, parece que existe uma taxa alta de cancelamento no serviço. Para podermos cravar esta hipótese necessitaríamos conhecer a taxa de adesão também, mas não será nosso caso. Iremos trabalhar com os motivos que levam a esse cancelamento, quais colunas influenciam direta ou indiretamente esse resulyado. Logo é de extrema importância podermos dar um parecer técnico as lideranças.